plugins {
	id 'fabric-loom' version '1.6-SNAPSHOT'
	id 'maven-publish'
	//id 'com.github.johnrengelman.shadow' version '7.1.2'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {}

loom {
    splitEnvironmentSourceSets()

	mods {
		"rules4worlds-fabric" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

}

fabricApi {
	//configureDataGeneration()
}

dependencies {
	modImplementation "net.fabricmc:fabric-loader:0.15.11"
	if (minecraft_version == "1.20.2") {
		minecraft "com.mojang:minecraft:1.20.2"
		mappings "net.fabricmc:yarn:1.20.2+build.4:v2"
		modImplementation "net.fabricmc.fabric-api:fabric-api:0.91.6+1.20.2"
	}
	if (minecraft_version == "1.20.3") {
		minecraft "com.mojang:minecraft:1.20.3"
		mappings "net.fabricmc:yarn:1.20.3+build.1:v2"
		modImplementation "net.fabricmc.fabric-api:fabric-api:0.91.1+1.20.3"
	}
	if (minecraft_version == "1.20.4") {
		minecraft "com.mojang:minecraft:1.20.4"
		mappings "net.fabricmc:yarn:1.20.4+build.3:v2"
		modImplementation "net.fabricmc.fabric-api:fabric-api:0.97.1+1.20.4"
	}
}

processResources {
	inputs.property "mod_version", project.version
	inputs.property "minecraft_version", project.minecraft_version
	inputs.property "min_minecraft_version", project.min_minecraft_version
	inputs.property "max_minecraft_version", project.max_minecraft_version
	inputs.property "loader_version", project.loader_version
	filteringCharset "UTF-8"

	filesMatching("fabric.mod.json") {
		expand "mod_version": project.version,
				"minecraft_version": project.minecraft_version,
				"min_minecraft_version": project.min_minecraft_version,
				"max_minecraft_version": project.max_minecraft_version,
				"loader_version": project.loader_version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("rules4worlds", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	repositories {
		mavenLocal()
	}
}