plugins {
	id 'fabric-loom' version '1.6-SNAPSHOT'
	id 'maven-publish'
	//id 'com.github.johnrengelman.shadow' version '7.1.2'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {}

loom {
    splitEnvironmentSourceSets()

	mods {
		"rules4worlds-fabric" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

}

fabricApi {
	//configureDataGeneration()
}

dependencies {
	minecraft "com.mojang:minecraft:${minecraft_version}"
	modImplementation "net.fabricmc:fabric-loader:0.15.11"

	def versions = [
		"1.19"   : [yarnVersion: "1.19+build.4", apiVersion: "0.58.0+1.19"],
		"1.19.1" : [yarnVersion: "1.19.1+build.6", apiVersion: "0.58.5+1.19.1"],
		"1.19.2" : [yarnVersion: "1.19.2+build.28", apiVersion: "0.77.0+1.19.2"],
		"1.19.3" : [yarnVersion: "1.19.3+build.5", apiVersion: "0.76.1+1.19.3"],
		"1.19.4" : [yarnVersion: "1.19.4+build.2", apiVersion: "0.87.2+1.19.4"]
	]

	def versionConfig = versions[minecraft_version]

	if (versionConfig) {
		mappings "net.fabricmc:yarn:${versionConfig.yarnVersion}:v2"
		modImplementation "net.fabricmc.fabric-api:fabric-api:${versionConfig.apiVersion}"
	} else {
		throw new GradleException("Unsupported Minecraft version: $minecraft_version")
	}
}

processResources {
	inputs.property "mod_version", project.version
	inputs.property "minecraft_version", project.minecraft_version
	inputs.property "min_minecraft_version", project.min_minecraft_version
	inputs.property "max_minecraft_version", project.max_minecraft_version
	inputs.property "loader_version", project.loader_version
	filteringCharset "UTF-8"

	filesMatching("fabric.mod.json") {
		expand "mod_version": project.version,
				"minecraft_version": project.minecraft_version,
				"min_minecraft_version": project.min_minecraft_version,
				"max_minecraft_version": project.max_minecraft_version,
				"loader_version": project.loader_version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("rules4worlds", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	repositories {
		mavenLocal()
	}
}